Wildcat.App/Areas/MCNJ/Controllers/HeatTreatMaterials/ConformanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Wildcat.App.ViewModels.MCNJ.HeatTreatMaterials;
using Wildcat.Entities.MCNJ.HeatsSecured;
using Wildcat.Utilities;

namespace Wildcat.App.Controllers.MCNJ.HeatTreatMaterials
{
    [Area("MCNJ")]
    public class ConformanceController : Controller
    {
        #region Private Fields

        private readonly IHttpContextAccessor _httpContextAccessor;
        private HeatsSecuredContext _context;
        private IViewRenderService _viewRenderService;

        private const int LOGON32_PROVIDER_DEFAULT = 0;

        //This parameter causes LogonUser to create a primary token.
        private const int LOGON32_LOGON_INTERACTIVE = 2;

        #endregion Private Fields



        #region Public Properties
        #endregion Public Properties



        #region Constructors

        public ConformanceController(IHttpContextAccessor httpContextAccessor, HeatsSecuredContext context, IViewRenderService viewRenderService)
        {
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            _viewRenderService = viewRenderService;
        }

        #endregion Constructors



        #region Pages   

        public IActionResult Index()
        {
            ConformanceCertsViewModel vm = new ConformanceCertsViewModel();
            return View(vm.Certs);
        }

        public IActionResult Add()
        {
            AddConformanceCertsViewModel vm = new AddConformanceCertsViewModel(_context, _viewRenderService);
            return View(vm);
        }

        public IActionResult Edit(string id)
        {
            EditConformanceCertsViewModel vm = new EditConformanceCertsViewModel(_context, _viewRenderService, id);
            return View(vm);
        }

        #endregion Pages



        #region Api

        public JsonResult EditHeatPartial(string ID)
        {
            SelectEditHeatResponse response = new SelectEditHeatResponse(_context, _viewRenderService, ID);
            return Json(response);
        }

        [HttpPost]
        public JsonResult AddResult(int McWCn, int? Crn, DateTime? Date, int? CustId, string CustPo, string Heat, string GsMcW, string Hardness, string HeatTreatNotes, string CertificationNotes, string ProcessNo, string NoteType, int? QtyShipped, string Die, string WorkOrder)
        {
            AddConfResponse response = new AddConfResponse(_context, _viewRenderService, McWCn, Crn, Date, CustId, CustPo, Heat, GsMcW, Hardness, HeatTreatNotes, CertificationNotes, ProcessNo, NoteType, QtyShipped, Die, WorkOrder, _httpContextAccessor.HttpContext.User.Identity.Name);
            return Json(response);
        }

        [HttpPost]
        public JsonResult EditResult(int McWCn, int? Crn, DateTime? Date, int? CustId, string CustPo, string Heat, string GsMcW, string Hardness, string HeatTreatNotes, string CertificationNotes, string ProcessNo, string NoteType, int? QtyShipped, string Die, string WorkOrder)
        {
            EditConfResponse response = new EditConfResponse(_context, _viewRenderService, McWCn, Crn, Date, CustId, CustPo, Heat, GsMcW, Hardness, HeatTreatNotes, CertificationNotes, ProcessNo, NoteType, QtyShipped, Die, WorkOrder, _httpContextAccessor.HttpContext.User.Identity.Name);
            return Json(response);
        }

        [HttpPost]
        public JsonResult AddOpResult(int? ControlNo, int? Crn, string ProcessNo, string WorkOrder, string Woqty, string McwHtCodes, int RowId)
        {
            AddConfOpResponse response = new AddConfOpResponse(_context, _viewRenderService, ControlNo, Crn, ProcessNo, WorkOrder, Woqty, McwHtCodes, RowId, _httpContextAccessor.HttpContext.User.Identity.Name);
            return Json(response);
        }

        [HttpPost]
        public JsonResult EditOpResult(int? Crn, string ProcessNo, string WorkOrder, string Woqty, string McwHtCodes, int RowId)
        {
            EditConfOpResponse response = new EditConfOpResponse(_context, _viewRenderService, null, Crn, ProcessNo, WorkOrder, Woqty, McwHtCodes, RowId, _httpContextAccessor.HttpContext.User.Identity.Name);
            return Json(response);
        }

        [HttpPost]
        public JsonResult AutoCompleteHeat(string prefix)
        {
            var mills = (from mill in _context.CertsMill
                        where mill.Heat.StartsWith(prefix.ToUpper())
                        || mill.Heat.StartsWith(prefix.ToUpper())
                        select new
                        {
                            label = mill.Heat,
                            val = mill.Heat
                        }).ToList();

            return Json(mills);
        }

        [HttpPost]
        public JsonResult GetHeatInfo(string prefix)
        {
            var mills = (from mill in _context.CertsMill
                         where mill.Heat.Equals(prefix)
                         select mill);

            return Json(mills);
        }

        [HttpPost]
        public JsonResult AutoCompleteDies(string prefix)
        {
            //_context entities = new NorthwindEntities();
            var dies = (from die in _context.Dies
                        where die.Die.StartsWith(prefix.ToUpper())
                        select new
                        {
                            label = die.Die,
                            val = die.Die
                        }).ToList();

            return Json(dies);
        }

        [HttpPost]
        public JsonResult GetDiesInfo(string prefix)
        {
            var dies = from die in _context.Dies
                       where die.Die.Equals(prefix.ToUpper())
                       select die;

            return Json(dies);
        }

        [HttpPost]
        public ActionResult AjaxGetJsonData(int draw, int start, int length)
        {
            int TOTAL_ROWS = 0;
            string search = _httpContextAccessor.HttpContext.Request.Form.Where(x => x.Key == "search[value]").FirstOrDefault().Value;
            int sortColumn = Convert.ToInt32(_httpContextAccessor.HttpContext.Request.Form.Where(x => x.Key == "order[0][column]").FirstOrDefault().Value);
            string sortDirection = _httpContextAccessor.HttpContext.Request.Form.Where(x => x.Key == "order[0][dir]").FirstOrDefault().Value;
            if (length == -1)
            {
                length = TOTAL_ROWS;
            }

            ConformanceCertDataTableData dataTableData = new ConformanceCertDataTableData(_context, _viewRenderService, draw, start, length, search, sortColumn, sortDirection);

            return Json(dataTableData.set);
        }

        #endregion Api    
    }
}

Wildcat.App/Areas/MCNJ/Controllers/HeatTreatMaterials/PackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Wildcat.App.ViewModels.MCNJ.HeatTreatMaterials;
using Wildcat.Entities.MCNJ.HeatsSecured;
using Wildcat.Utilities;

namespace Wildcat.App.Controllers.MCNJ.HeatTreatMaterials
{
    [Area("MCNJ")]
    public class PackingController : Controller
    {
        #region Private Fields

        private readonly IHttpContextAccessor _httpContextAccessor;
        private HeatsSecuredContext _context;
        private IViewRenderService _viewRenderService;

        private const int LOGON32_PROVIDER_DEFAULT = 0;

        //This parameter causes LogonUser to create a primary token.
        private const int LOGON32_LOGON_INTERACTIVE = 2;

        #endregion Private Fields



        #region Public Properties
        #endregion Public Properties



        #region Constructors

        public PackingController(IHttpContextAccessor httpContextAccessor, HeatsSecuredContext context, IViewRenderService viewRenderService)
        {
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            _viewRenderService = viewRenderService;
        }

        #endregion Constructors



        #region Pages   

        public IActionResult Index()
        {
            PackingSlipsViewModel vm = new PackingSlipsViewModel();
            return View(vm.PackingSlip);
        }

        public IActionResult Add()
        {
            AddPackingSlipsViewModel vm = new AddPackingSlipsViewModel(_context);

            //MetRecordViewModel vm = new MetRecordViewModel();
            //vm.MetRecords = new List<Entities.MCNJ.SecureHeatTreatBatchBook.TblMetRecords>();
            //vm.MetRecords = _context.TblMetRecords.Take(100).ToList();
            return View(vm);
        }

        public IActionResult Edit(int PSN)
        {
            EditPackingSlipsViewModel vm = new EditPackingSlipsViewModel(_context, PSN);

            //vm.PackingSlip = _context.TblPackingSlips.Where(x => x.Psn == PSN).FirstOrDefault();
            //vm.ShipTo = new TblCustomers();
            //vm.SoldTo = new TblCustomers();
            
            //vm.Die = vm.PackingSlip.Die;
            //foreach (var p in _context.TblPackingSlips)
            //{
            //    vm.Dies.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem(p.Die, p.Die));
            //}

            //foreach (var c in _context.TblCustomers)
            //{
            //    vm.Customers.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem(c.CustomerName, c.CustId.ToString()));
            //}

            //foreach(var l in vm.Freight)
            //{
            //    if(l.Value == vm.PackingSlip.Freight)
            //    {
            //        l.Selected = true;
            //    }
            //}

            //var die = _context.Dies.Where(x => x.Die == vm.PackingSlip.Die).FirstOrDefault();

            //vm.PackingSlip.Die = die.Die;  vm.PartNumber = die.PartNum; vm.RevisionNumber = die.Revision;

            //if(vm.PackingSlip.ShipTo != null)
            //{
            //    var ShipTo = _context.TblCustomers.Where(x => x.CustId == vm.PackingSlip.ShipTo).FirstOrDefault();
            //    if (ShipTo != null)
            //    {
            //        vm.ShipTo = ShipTo;
            //    }
            //}

            //if (vm.PackingSlip.SoldTo != null)
            //{
            //    var SoldTo = _context.TblCustomers.Where(x => x.CustId == vm.PackingSlip.SoldTo).FirstOrDefault();
            //    if(SoldTo != null)
            //    {
            //        vm.SoldTo = SoldTo;
            //    }
            //}

            return View(vm);
        }

        #endregion Pages



        #region Api

        [HttpPost]
        public JsonResult AddResult(string McWCn, DateTime? Date, string Die, string WorkOrder, string CustPo, short Quantity, string ProcessNo, string SerialNumber, string Freight, string ItemNumber, string ShipVia, int? NumberOfSkids, int? NumberOfBoxes, int? TotalWeight, string Notes, bool ShipAir, int? Crn2, int? Crn, int? ShipTo, int? SoldTo)
        {
            AddPackingSlipResponse response = new AddPackingSlipResponse(_context, _viewRenderService, McWCn, Date, Die, WorkOrder, CustPo, Quantity, ProcessNo, SerialNumber, Freight, ItemNumber, ShipVia, NumberOfSkids, NumberOfBoxes, TotalWeight, Notes, ShipAir, Crn2, Crn, ShipTo, SoldTo, _httpContextAccessor.HttpContext.User.Identity.Name);
            return Json(response);
        }

        [HttpPost]
        public JsonResult EditResult(int Psn, string McWCn, DateTime? Date, string Die, string WorkOrder, string CustPo, short Quantity, string ProcessNo, string SerialNumber, string Freight, string ItemNumber, string ShipVia, int? NumberOfSkids, int? NumberOfBoxes, int? TotalWeight, string Notes, bool ShipAir, int? Crn2, int? Crn, int? ShipTo, int? SoldTo)
        {
            EditPackingSlipResponse response = new EditPackingSlipResponse(_context, _viewRenderService, Psn, McWCn, Date, Die, WorkOrder, CustPo, Quantity, ProcessNo, SerialNumber, Freight, ItemNumber, ShipVia, NumberOfSkids, NumberOfBoxes, TotalWeight, Notes, ShipAir, Crn2, Crn, ShipTo, SoldTo, _httpContextAccessor.HttpContext.User.Identity.Name);
            return Json(response);
        }

        [HttpPost]
        public JsonResult AutoCompleteDies(string prefix)
        {
            //_context entities = new NorthwindEntities();
            var dies = (from die in _context.Dies
                        where die.Die.StartsWith(prefix.ToUpper())
                        select new
                        {
                            label = die.Die,
                            val = die.Die
                        }).ToList();
            //var diesx = (from die in _context.Dies
            //            where die.Die.Contains(prefix.ToUpper())
            //            select new
            //            {
            //                label = die.Die,
            //                val = die.Die
            //            }).ToList();

            return Json(dies);
        }

        [HttpPost]
        public JsonResult GetDiesInfo(string prefix)
        {
            var dies = from die in _context.Dies
                        where die.Die.Equals(prefix.ToUpper())
                        select die;

            return Json(dies);
        }

        [HttpPost]
        public JsonResult AutoCompleteCustomers(string prefix)
        {
            var customers = (from customer in _context.TblCustomers
                            where customer.CustomerName.StartsWith(prefix.ToUpper())
                            select new
                            {
                                label = customer.CustomerName,
                                val = customer.CustId
                            }).ToList();

            return Json(customers);

        }

        [HttpPost]
        public JsonResult GetCustomerInfo(int prefix)
        {
            //var id = Convert.ToInt32(prefix);
            //_context entities = new NorthwindEntities();
            var customers = from customer in _context.TblCustomers
                             where customer.CustId.Equals(prefix)
                            select customer;
            //var diesx = (from die in _context.Dies
            //            where die.Die.Contains(prefix.ToUpper())
            //            select new
            //            {
            //                label = die.Die,
            //                val = die.Die
            //            }).ToList();

            return Json(customers);
        }

        [HttpPost]
        public JsonResult AutoCompleteShipVia(string prefix)
        {
            var shipvias = (from shipvia in _context.TblPackingSlips
                             where shipvia.ShipVia.StartsWith(prefix.ToUpper())
                             select new
                             {
                                 label = shipvia.ShipVia,
                                 val = shipvia.ShipVia
                             }).ToList().Distinct();

            return Json(shipvias);

        }

        [HttpGet]
        public ActionResult AjaxGetJsonData(int draw, int start, int length)
        {
            int TOTAL_ROWS = 0;
            string search = _httpContextAccessor.HttpContext.Request.Query.Where(x => x.Key == "search[value]").FirstOrDefault().Value;
            int sortColumn = Convert.ToInt32(_httpContextAccessor.HttpContext.Request.Query.Where(x => x.Key == "order[0][column]").FirstOrDefault().Value);
            string sortDirection = _httpContextAccessor.HttpContext.Request.Query.Where(x => x.Key == "order[0][dir]").FirstOrDefault().Value;
            if (length == -1)
            {
                length = TOTAL_ROWS;
            }

            PackingDataTableData dataTableData = new PackingDataTableData(_context, _viewRenderService, draw, start, length, search, sortColumn, sortDirection);

            //// note: we only sort one column at a time
            //if (_httpContextAccessor.HttpContext.Request.QueryString.Value.Equals("order[0][column]").ToString() != null)
            //{TblPackingSlips
            //    sortColumn = int.Parse(_httpContextAccessor.HttpContext.Request.QueryString.Value.Equals("order[0][column]").ToString());
            //}
            //if (_httpContextAccessor.HttpContext.Request.QueryString.Value.Equals("order[0][dir]").ToString() != null)
            //{
            //    sortDirection = _httpContextAccessor.HttpContext.Request.QueryString.Value.Equals("order[0][dir]").ToString();
            //}

            //DataTableData dataTableData = new DataTableData();
            //dataTableData.draw = draw;
            //dataTableData.recordsTotal = TOTAL_ROWS = _context.TblPackingSlips.Count();
            //int recordsFiltered = 0;

Wildcat.App/Areas/MCNJ/Views/HeatTreatMaterials/Packing/Index.cshtml
@model List<Wildcat.Entities.MCNJ.HeatsSecured.TblPackingSlips>
@{
    ViewData["Title"] = "Index";
}

<h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="breadcrumb-item" href="/Home/Index">Home</a>
            </li>
            <li class="breadcrumb-item active">Packing Slips</li>
        </ol>
    </div>
</h4>

<div class="card">

    <h5 class="card-header text-align-center">
        Packing Slips
        @Html.ActionLink("New Packing Slip", "Add", "Packing", null, new { @class = "btn btn-primary pull-right" })
        @*<button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#modals-default">New Job</button>*@
    </h5>
    <div class="card-datatable table-responsive">
        @*@await Component.InvokeAsync("RawScanJobs", new { _vm = Model })*@
        <table class="datatables-demo table table-striped table-bordered display nowrap" id="m_table_2">
            <thead>
                <tr>
                    <th>PSN</th>
                    <th>McW-CN</th>
                    <th>Die</th>
                    <th>Work Order</th>
                    <th>Cust-PO</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model)
                {
                <tr>
                    <td>@i.Psn</td>
                    <td>@i.McWCn</td>
                    <td>@i.Die</td>
                    <td>@i.WorkOrder</td>
                    <td>@i.CustPo</td>
                    <td>@i.Date.Value.ToShortDateString()</td>
                    <td style="text-align:center;">
                        <button type="button" style="display:block;margin:auto;" class="btn btn-primary btn-sm openbtn" onclick="location.href='@Url.Action("Edit", "Packing", new { PSN = i.Psn })'">EDIT</button>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>

    $(document).ready(function () {
        $('#m_table_2').dataTable({
            "processing": true,
            "serverSide": true,
            //"search":
            //"info": true,
            //"stateSave": true,
            "lengthMenu": [[10, 20, 50, -1], [10, 20, 50, "All"]],
            "ajax": {
                "url": "/MCNJ/HeatTreatMaterials/Packing/AjaxGetJsonData",
                "type": "GET"
            },
            "language": {
                "search": "",
                "searchPlaceholder": "Search..."
            },
            "columns": [
                { "data": "Psn", "orderable": false },
                { "data": "McWCn", "orderable": true },
                { "data": "Die", "orderable": true },
                { "data": "WorkOrder", "orderable": true },
                { "data": "CustPo", "orderable": true },
                { "data": "Date", "orderable": false },
                {
                    "data": null,
                    "className": "text-center",
                    "render": function (data, type, item) {
                        //return '<button type="button" style="display:block;margin:auto;" class="btn btn-primary btn-sm openbtn" data-id="' + data.McWCn + '" title="Edit">Edit</i></button>';
                        return '<a href=/MCNJ/HeatTreatMaterials/Packing/Edit?PSN=' + data.Psn + ' type="button" style="text-align:center;margin:0 auto;" class="btn btn-primary btn-sm openbtn editopenbtn">EDIT</a>';
                    },
                    "orderable": false
                }
            ],
            "order": [[0, "asc"]]
        });
    });



    //$('#m_table_2 tbody').on('click', '.editopenbtn', function (e) {
    //    var id = e.currentTarget.dataset.value;
    //    $.blockUI({
    //        message: '<div class="sk-folding-cube sk-primary"><div class="sk-cube1 sk-cube"></div><div class="sk-cube2 sk-cube"></div><div class="sk-cube4 sk-cube"></div><div class="sk-cube3 sk-cube"></div></div><h5 style="color: #444">LOADING...</h5>',
    //        css: {
    //            backgroundColor: 'transparent',
    //            border: '0',
    //            zIndex: 9999999
    //        },
    //        overlayCSS: {
    //            backgroundColor: '#fff',
    //            opacity: 0.8,
    //            zIndex: 9999990
    //        }
    //    });

    //    $.ajax({
    //        url: "/MCNJ/HeatTreatBatchRecords/Dies/EditDiePartial/?ID=" + encodeURIComponent(id),
    //        type: "GET",
    //        cache: false,
    //        success: function (result) {
    //            $.unblockUI();

    //            $('#edit-modal-form').html(result.Form.Result);
    //            //$('#m_table_2').DataTable({
    //            //    scrollY: '50vh',
    //            //    scrollX: true,
    //            //    scrollCollapse: true,
    //            //    columnDefs: [{
    //            //        orderable: false,
    //            //        className: 'select-checkbox',
    //            //        targets: 0
    //            //    }],
    //            //    select: {
    //            //        style: 'multi',
    //            //        selector: 'td:first-child'
    //            //    }
    //            //});
    //            $('#modals-default-edit').modal('show');

    //        },
    //        error: function (result) {
    //            $.unblockUI();

    //            $.growl.error({
    //                message: result.statusText
    //            });
    //        }

    //    });

    //    return false;
    //});

</script>